export enum ButtonCustomId {
  ADMIN_CHANNEL = 'ADMIN_CHANNEL',
  SETUP_START = 'SETUP_START',
  SETUP_DONE = 'SETUP_DONE',
  EDIT_ADMIN_CHANNEL = 'EDIT_ADMIN_CHANNEL',
  EDIT_LOG_CHANNEL = 'EDIT_LOG_CHANNEL',
  EDIT_POINT_PERIOD = 'EDIT_POINT_PERIOD',
  POINT_PERIOD = 'POINT_PERIOD',
  SETTINGS = 'SETTINGS',
  NEW_POINT_UNIT_ADD = 'NEW_POINT_UNIT_ADD',
}
